### ISSUE TITLE
null reference

### ISSUE THREAD

**Issue by kstacey** [kstacey/Maze-Tank#1]
https://github.com/kstacey/Maze-Tank/blob/2d7e94d66a6a7cff90d07346425c50b53971c878/Assets/Scripts/Managers/Enemy_Manager.cs#L37

**Comment by mpintar** [comment]
Opened a PR to show a different way to do this, with the changes to the scene that makes it not throw exceptions 

https://github.com/kstacey/Maze-Tank/pull/3
